#!/bin/sh

env WINEPREFIX="/home/tonitch/.steam/steam/steamapps/compatdata/252950/pfx" WINEESYNC=1 ~/.steam/steam/compatibilitytools.d/Proton-5.6-GE-2/dist/bin/wine64 /home/tonitch/Documents/rocketleague/BakkesMod.exe
