#!/bin/sh

env WINEPREFIX="/home/tonitch/Public/OneTODisk/SteamLibrary/steamapps/compatdata/271590/pfx" WINEESYNC=1 ~/.steam/steam/compatibilitytools.d/Proton-5.6-GE-2/dist/bin/wine64 /home/tonitch/Documents/gtaonline/modest_menu-v0.8.7/modest-menu.exe
